/* Generated by tools.py gen_blob from model/net_blob.bin - do not edit. */
#pragma once
#define BLOB_FLASH_ADDR 0x200000u
#define BLOB_BYTES 48616u
#define BLOB_RECORDS 4050u
#define BLOB_STYLES 3u
#define BLOB_CRC32 0x373deed7u
