"""StyleCam firmware helpers.

gen_seq: rtl/sc431hai/sc_sequence.vh (validated SC431HAI table) -> src/sc431hai_seq.h
mkrom:   build/stylecam.bin -> four byte-lane $readmemb files for the Sapphire on-chip RAM,
         written next to the IP (ip/soc) and into fw_rom/ for build.py.
"""
import re, sys
from pathlib import Path
HERE = Path(__file__).resolve().parent
PROJ = HERE.parents[4]                      # .../StyleCam_camera
RAM_BYTES = 16384


def gen_seq():
    src = (PROJ / 'rtl/sc431hai/sc_sequence.vh').read_text()
    consts = dict(re.findall(r"(\w+_INDEX)=8'd(\d+)", src))
    rows = re.findall(r"8'd(\d+): sequence_word=\{2'd(\d),16'h([0-9a-fA-F]{4}),8'h([0-9a-fA-F]{2})\};", src)
    rows = sorted((int(i), int(op), int(a, 16), int(d, 16)) for i, op, a, d in rows)
    assert [r[0] for r in rows] == list(range(len(rows))), 'sequence must be contiguous'
    out = ['/* Generated by tools.py gen_seq from rtl/sc431hai/sc_sequence.vh - do not edit. */',
           '/* word = op<<24 | reg<<8 | data; op 0 write, 1 read+verify, 2 delay(reg = ms), 3 diagnostic read */',
           '#pragma once', '#include <stdint.h>']
    for k in ['CONFIG_DONE_INDEX', 'STREAM_INDEX', 'DIAG_FIRST_INDEX', 'LAST_INDEX']:
        out.append(f'#define SC_{k} {consts[k]}')
    out.append(f'#define SC_SEQ_LEN {len(rows)}')
    out.append('static const uint32_t sc_seq[SC_SEQ_LEN] = {')
    for i in range(0, len(rows), 6):
        out.append('    ' + ','.join(f'0x{op:02x}{a:04x}{d:02x}' for _, op, a, d in rows[i:i + 6]) + ',')
    out.append('};')
    (HERE / 'src/sc431hai_seq.h').write_text('\n'.join(out) + '\n')
    print('sequence entries', len(rows))


def mkrom():
    data = (HERE / 'build/stylecam.bin').read_bytes()
    assert len(data) <= RAM_BYTES, f'firmware {len(data)} B exceeds on-chip RAM {RAM_BYTES} B'
    data = data + bytes(RAM_BYTES - len(data))
    for dest in [PROJ / 'ip/soc', PROJ / 'fw_rom']:
        dest.mkdir(exist_ok=True)
        for lane in range(4):
            lines = [format(data[i + lane], '08b') for i in range(0, RAM_BYTES, 4)]
            (dest / f'EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol{lane}.bin').write_text('\n'.join(lines) + '\n')
    print(f'firmware {len(data.rstrip(bytes(1)))} B of {RAM_BYTES} B -> ip/soc and fw_rom')


if __name__ == '__main__':
    {'gen_seq': gen_seq, 'mkrom': mkrom}[sys.argv[1]]()
